#!/bin/bash
# .claude/hooks/learning/skill-retrospective.sh
# Stop hook: Capture feedback when skills/agents are used to improve them over time
#
# This hook creates a self-improving feedback loop:
# - Detects which skills/agents were used during the session
# - Asks targeted questions about the experience
# - Stores feedback for review and integration
# - Skills get better with every use
#
# Exit codes:
#   0 = success (always, non-blocking)

# Check if we're in a git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    exit 0
fi

# Create feedback directory if it doesn't exist
mkdir -p .claude/feedback

# Detect skills/agents used in this session
# Look for skill invocations in recent git commits or session logs
SKILLS_USED=$(git log --since="2 hours ago" --all-match --grep="/[a-z-]*" --oneline 2>/dev/null | \
    grep -oE "/[a-z-]+" | sort -u | sed 's/\///' || echo "")

# Also check for explicit skill references in recent work
if [ -d ".claude/skills" ]; then
    # Count recent file reads on skill files (if tracked somehow)
    # For now, we'll rely on commit messages and explicit skill mentions
    :
fi

# Only ask for feedback if skills were actually used
if [ -z "$SKILLS_USED" ]; then
    # No detected skill usage, skip retrospective
    exit 0
fi

# Check if we've already asked recently (avoid survey fatigue)
LAST_RETRO_FILE=".claude/feedback/.last-retrospective"
if [ -f "$LAST_RETRO_FILE" ]; then
    LAST_RETRO=$(cat "$LAST_RETRO_FILE")
    NOW=$(date +%s)
    # Only ask once per day maximum
    if [ $((NOW - LAST_RETRO)) -lt 86400 ]; then
        exit 0
    fi
fi

# Count uncommitted changes and recent commits
UNCOMMITTED=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
RECENT_COMMITS=$(git log --since="2 hours ago" --oneline 2>/dev/null | wc -l | tr -d ' ')

# Only trigger retrospective if significant work happened
if [ "$UNCOMMITTED" -eq 0 ] && [ "$RECENT_COMMITS" -eq 0 ]; then
    exit 0
fi

echo ""
echo "🔄 Skill Retrospective"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "I noticed you used some skills/agents this session:"
echo "$SKILLS_USED" | while read -r skill; do
    echo "  - /$skill"
done
echo ""
echo "💡 Quick feedback (helps improve these skills for everyone):"
echo ""
echo "1. Did any skill miss important steps? (y/n/skip)"
read -r MISSED_STEPS

echo "2. Were the benchmarks/numbers accurate for your context? (y/n/skip)"
read -r BENCHMARKS_ACCURATE

echo "3. What would make these skills more helpful? (enter text or 'skip')"
read -r IMPROVEMENTS

echo "4. Did you have to clarify or correct the skill's approach? (y/n/skip)"
read -r NEEDED_CORRECTIONS

# Store feedback with timestamp
TIMESTAMP=$(date +%Y-%m-%d-%H%M%S)
FEEDBACK_FILE=".claude/feedback/retro-$TIMESTAMP.md"

cat > "$FEEDBACK_FILE" <<EOF
# Retrospective: $(date +"%Y-%m-%d %H:%M")

## Skills Used
$SKILLS_USED

## Feedback

**Missed important steps?** $MISSED_STEPS

**Benchmarks accurate?** $BENCHMARKS_ACCURATE

**Improvements needed:**
$IMPROVEMENTS

**Needed corrections?** $NEEDED_CORRECTIONS

## Session Context
- Uncommitted files: $UNCOMMITTED
- Recent commits: $RECENT_COMMITS
- Commits:
$(git log --since="2 hours ago" --oneline 2>/dev/null | head -5)

## Next Steps
- [ ] Review feedback and identify patterns
- [ ] Update skill files if feedback is actionable
- [ ] Consider adding missing steps or clearer benchmarks
- [ ] Archive this feedback once processed

---
*Generated by skill-retrospective hook*
EOF

echo ""
echo "✅ Feedback saved to: $FEEDBACK_FILE"
echo ""
echo "📌 To review all feedback:"
echo "   ls .claude/feedback/"
echo ""
echo "📌 To update a skill based on feedback:"
echo "   1. Review feedback patterns in .claude/feedback/"
echo "   2. Edit the skill file: .claude/skills/[skill-name]/SKILL.md"
echo "   3. Add a '## Learnings' section with feedback insights"
echo "   4. Update the main content if needed"
echo ""

# Mark that we asked for retrospective
date +%s > "$LAST_RETRO_FILE"

exit 0
